{% set name = "stdcompat" %}
{% set version = "0.0.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/robertu94/std_compat/archive/{{ version }}.tar.gz
  sha256: 1287251b694adb80210536ab6eb75c1ff2c4ed8b77023208a757ae27c9dae0bb 

build:
  skip: True  # [win or osx]
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - pkg-config
    - boost-cpp
  run:
    - boost-cpp

about:
  home: https://github.com/robertu94/std_compat
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYRIGHT.txt
  summary: 'Set of compatibility headers for C++ 14, 17, and 20 for C++11'
  description: |
    LibStdCompat is a set of compatibility headers for C++ 14, 17, and
    20 for C++11. It aims to be lighter weight and more narrowly
    tailored than some other alternatives such as Boost or replacing
    your standard library with libcxx when certain fewer features are
    needed.
  doc_url: https://github.com/robertu94/std_compat/blob/master/README.markdown
  dev_url: https://github.com/robertu94/std_compat

